#!/usr/bin/env ruby

require "json"

require "hyper_sh"

input = JSON.parse(STDIN.read)

source = input["source"]
params = input["params"]

deployer = HyperSH::Deployer.new
commands = deployer.prepare(source).deploy(params)
commands.each do |c|
  puts HyperSH::CommandRunner.new.run(c).output
end

